-- Table: public."Phone"

-- DROP TABLE public."Phone";

CREATE TABLE public."Phone"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "Number" text COLLATE pg_catalog."default",
    "IsWhatsApp" boolean NOT NULL,
    CONSTRAINT "PK_Phone" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE public."Phone"
    OWNER to postgres;

-- Table: public."Email"

-- DROP TABLE public."Email";

CREATE TABLE public."Email"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "EmailAddress" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Email" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE public."Email"
    OWNER to postgres;

-- Table: public."Person"

-- DROP TABLE public."Person";

CREATE TABLE public."Person"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "PhoneId" bigint,
    "EmailId" bigint,
    CONSTRAINT "PK_Person" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Person_Email_EmailId" FOREIGN KEY ("EmailId")
        REFERENCES public."Email" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
        NOT VALID,
    CONSTRAINT "FK_Person_Phone_PhoneId" FOREIGN KEY ("PhoneId")
        REFERENCES public."Phone" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE public."Person"
    OWNER to postgres;

-- Index: IX_Person_EmailId

-- DROP INDEX public."IX_Person_EmailId";

CREATE INDEX "IX_Person_EmailId"
    ON public."Person" USING btree
    ("EmailId")
    TABLESPACE pg_default;

-- Index: IX_Person_PhoneId

-- DROP INDEX public."IX_Person_PhoneId";

CREATE INDEX "IX_Person_PhoneId"
    ON public."Person" USING btree
    ("PhoneId")
    TABLESPACE pg_default;

