-- Table: public."Person"

-- DROP TABLE public."Person";

CREATE TABLE public."Person"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Person" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE public."Person"
    OWNER to postgres;

-- Table: public."Email"

-- DROP TABLE public."Email";

CREATE TABLE public."Email"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "EmailAddress" text COLLATE pg_catalog."default",
    "IsPrimary" boolean NOT NULL,
    "PersonId" bigint NOT NULL,
    "Type" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Email" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Email_Person_PersonId" FOREIGN KEY ("PersonId")
        REFERENCES public."Person" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE public."Email"
    OWNER to postgres;

-- Index: IX_Email_PersonId

-- DROP INDEX public."IX_Email_PersonId";

CREATE INDEX "IX_Email_PersonId"
    ON public."Email" USING btree
    ("PersonId")
    TABLESPACE pg_default;

-- Table: public."Phone"

-- DROP TABLE public."Phone";

CREATE TABLE public."Phone"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "Number" text COLLATE pg_catalog."default",
    "IsPrimary" boolean NOT NULL,
    "IsWhatsApp" boolean NOT NULL,
    "PersonId" bigint NOT NULL,
    "Type" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Phone" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Phone_Person_PersonId" FOREIGN KEY ("PersonId")
        REFERENCES public."Person" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE public."Phone"
    OWNER to postgres;

-- Index: IX_Phone_PersonId

-- DROP INDEX public."IX_Phone_PersonId";

CREATE INDEX "IX_Phone_PersonId"
    ON public."Phone" USING btree
    ("PersonId")
    TABLESPACE pg_default;